[package]
name = "executor-android"
version = "1.0.0"
edition = "2021"

[package.metadata.android]
assets = "../data"
strip = "strip"

[lib]
crate-type = ["cdylib"]

[dependencies]
blendshape = { path = "../game" }

[dependencies.fyrox]
workspace = true
