
[package]
name = "executor-android"
version = "0.1.0"
edition = "2021"

[package.metadata.android]
assets = "../data"
strip = "strip"

[lib]
crate-type = ["cdylib"]

[dependencies]
blendshape = { path = "../game" }

[dependencies.fyrox ]
git = "https://github.com/FyroxEngine/Fyrox"
